import "./globals.css";
import Header from "../components/layout/header";
import { AlertProvider } from "@/contexts/alert-context";
import { WebSocketProvider } from "@/contexts/websocket-context";

export const metadata = {
  title: "Woori-CodeShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning className="overflow-hidden">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {}
            `,
          }}
        />
        <meta name="grammarly-verification" content="off" />
        <style>
          {`
            ::-webkit-scrollbar {
              display: none;
            }
            * {
              -ms-overflow-style: none;
              scrollbar-width: none;
            }
          `}
        </style>
      </head>
      <body
        className="bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 overflow-hidden"
        suppressHydrationWarning
      >
        <WebSocketProvider>
          <AlertProvider>
            <Header />
            {children}
          </AlertProvider>
        </WebSocketProvider>
      </body>
    </html>
  );
}
